---
driver:
  name: vagrant
  customize:
    memory: 4096

provisioner:
  name: chef_zero
  require_chef_omnibus: 13.6.4

platforms:
  - name: centos-7.4
    driver:
      network:
      - ["forwarded_port", {guest: 8081, host: 8081}]

  - name: ubuntu-16.04
    driver:
      network:
      - ["forwarded_port", {guest: 8081, host: 8082}]

  - name: windows-2012r2
    driver:
      box: dhoer/windows-2012r2
      network:
      - ["forwarded_port", {guest: 8081, host: 8083}]

suites:
  - name: default
    run_list:
      - nexus3_test::default
      - nexus3_test::create_script
      - nexus3_test::delete_script
      - nexus3_test::run_script
    attributes:
       nexus3_test:
         connections_retries: 10
       nexus3:
         api:
           sensitive: false
           live_stream: false
           fail: false
