AllCops:
  Exclude:
    - '.kitchen/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Layout/MethodLength:
  Max: 60

Layout/AbcSize:
  Max: 60

Layout/BlockLength:
  Max: 130

Style/FormatString:
  Exclude: ['spec/**/*', 'test/**/*']

Style/FrozenStringLiteralComment:
  Enabled: false
